### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by kazuyahiko** [WilldooIT/Pentaho-reports-for-OpenERP#110]
Hi i have some issue in date
i use custom function in pentaho to return a date field from openerp
but when i see in the field in PRD it show the data type is string
however if i use standart function to retrieve that field it will show date data type
![image1](https://cloud.githubusercontent.com/assets/3387716/2763303/74b727ec-ca01-11e3-9a0d-3cba5c4a6c59.png)
![image2](https://cloud.githubusercontent.com/assets/3387716/2763304/79a583b6-ca01-11e3-9d02-0fe69ec915e0.png)

**Comment by richard-willdooit** [comment]
Without actually seeing the definition, I am really unable to comment too specifically.  I have not used custom functions on OpenERP data sources before, and this could be an oversight and problem, or could in fact be intentional behaviour.  Remember, the standard practice of OpenERP is to deal with date values as strings.  This may have been overlooked in this area, or may have been intentionally dealt with, but since the connector is not my area, this is the only light I can shed at this point.
