### ISSUE TITLE
Watermark - embedded Image -  Failed to load content using value

### ISSUE THREAD

**Issue by svenpetersen** [WilldooIT/Pentaho-reports-for-OpenERP#117]
Hello,

OpenERP v7.
pentaho Report Designer 5.0.1
Latest OpenERP Module and .war File (also tried building it, but it makes no difference).

Embedded Images in Page Header and Footer are working fine. Also Images stored in OpenERP.

But if I embed an Image in the Watermark section, it isn't printed if the Report is called from OpenERP, although it's displayed in the report designer's preview. 
From the Java Server log:
[java] Warning: Failed to load content using value bkgrd.PNG
[java] org.pentaho.reporting.libraries.resourceloader.ResourceKeyCreationException: Unable to create key: No loader was able to handle the given key data:bkgrd.PNG

thanks in advance!
Sven

**Comment by flotho** [comment]
Hy, when choosing an image, you could choose to embed or to link the image.
If you link the image, pentaho-openerp part will try to access relatively to your image locally to the server.
Try to embed instead of linking or try to store the image in a path that exists on your desktop AND on the server

**Comment by richard-willdooit** [comment]
@svenpetersen If you have followed flotho's advice and it is embedded, we will investigate further, but please confirm first if the image is definitely embedded and not linked.

**Comment by richard-willdooit** [comment]
@svenpetersen I am closing this as I have not heard back.
