### ISSUE TITLE
Correct parameters for pentaho report designer integration with odoo 

### ISSUE THREAD

**Issue by webappswiz** [WilldooIT/Pentaho-reports-for-OpenERP#209]
Hi there!

Let me start by saying a big thank you for the job you did on this module. 

I'm trying to integrate the Pentaho Report Designer into Odoo (version 8.0-6) setup on a Linux VM (Ubuntu 14.04) hosted on Azure.

I have gone as far as installing and running the report designer in the same root  folder where Odoo is installed. So for example, Odoo is installed here:
/opt/bitnami/apps/odoo/ 
and the report designer is installed here: 
/opt/bitnami/apps/report-designer/

I have 2 questions:
1. Is it okay to use the absolute URL of the Pentaho installation for the pentaho.server.url parameter?
So for example on our server, it would be something like /opt/bitnami/apps/report-designer/
1. How can I obtain the following paramters on our server:
   pentaho.openerp.xml.interface
   pentaho.openerp.xml.port

Thanks in anticipation of your assistance.

**Comment by webappswiz** [comment]
Oops, it seems the second question was truncated so I have reposted below:
1. How can I obtain the following paramters on our server:
   pentaho.openerp.xml.interface
   pentaho.openerp.xml.port

Thanks. 

Thanks in anticipation of your assistance.

Kind regards,

**Comment by flotho** [comment]
Hi @webappswiz,

I think you're confusing some parts. URL is not a physical path, so you'll have to set an ULR like http://yourhost:port/pentaho-reports-for-openerp
Additionnally, hosting pentaho report and odoo on the same machine is not really a bad idea, except if your odoo instance is highly used. In this case, you'll have to host it on another server.
Most Finally, If I were you I won't use the same physical path for 2 applications. Create 2 differents users (The one for odoo is already done), the other one for pentaho and store the server in its home so thatt this user will be able to run the server.
Finally, don't forget to cjek your firewall so that all the ports 8069/8080 are allowed from odoo to pentaho and vice versa.

regards

**Comment by richard-willdooit** [comment]
@webappswiz 

Has @flotho answered your query adequately? (thanks for that)  If you need to ask more questions, feel free to re-open this issue.
