### ISSUE TITLE
Pentaho Slower than iReport (When print many records)

### ISSUE THREAD

**Issue by dntq83** [WilldooIT/Pentaho-reports-for-OpenERP#84]
I'm create report using ORM in Pentaho and iReport, same object, same server. But when print Pentaho is slower than ireport (Same record). I checked log on OpenERP Server, pentaho many request to OpenERP and iReport request only one time.
Report file using Pentaho
https://kinden-openerp7.googlecode.com/svn/trunk/Reports/kderp_report_files/Purchase%20Order/Historical%20Data.prpt
Report file using iReport
https://kinden-openerp7.googlecode.com/svn/trunk/Reports/kderp_report_files/ROP_Ireport/historical_data.jrxml

**Comment by richard-willdooit** [comment]
Thankyou for the feedback.  The performance of Pentaho and how it accesses the data is beyond the scope of this project, and is an issue for Pentaho BI and the people who worked on the data connector.

If performance is an issue, you may find improvement by writing the data access as an SQL based query rather than using the object model.
